#spring.config.import=classpath:secrets.properties
#
#spring.datasource.url=jdbc:postgresql://localhost:5332/client
##spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#
#server.error.include-message=always



server:
  port: 8080
  error:
    include-message: "always"

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: us-east-2
  s3:
    buckets:
      client: bucketweb-test

spring:
  config:
    import: "classpath:secrets.properties"

  datasource:
    url: "jdbc:postgresql://localhost:5332/client"
    # url: "jdbc:postgresql://localhost:5432/postgres"

  jpa:
    hibernate:
      ddl-auto: "create-drop"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true


